## Script for merging all features
- Patients
- Lab Measures
- Afspraken

@TODO: Medicatie

In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import numpy as np
import plotly.express as px
from sklearn.cluster import KMeans


input_data = r'T:\lab_research\RES-Folder-UPOD\ODIN-UC4\E_ResearchData\2_ResearchData\20240805'
output_data = r'T:\lab_research\RES-Folder-UPOD\ODIN-UC4\G_Output\2_Data'

In [2]:
os.chdir(output_data)

In [3]:
df_afspraken = pd.read_csv(r'.\csv\df_afspraken.csv', index_col='studyId_0831')

df_lab = pd.read_parquet(r'.\parquet\lab_meas_final.parquet')

df_pat = pd.read_csv(r'.\csv\df_patients.csv', index_col='studyId_0831')

df_embeddings = pd.read_parquet(r'.\parquet\embeddings_perc.parquet')

In [4]:
df_afspraken

                                                 index_AfspCode  isEligible
studyId_0831
7992019       ['NFALG', 'NFALG', 'NFALG', 'NFALG', 'NFALG', ...           1
9812359                                      ['NFPOS', 'NFPOS']           0
22291801                   ['NFOST', 'NFOST', 'NFOST', 'NFOST']           0
29822615      ['NFPOS', 'NFPOS', 'NFPOS', 'NFPOS', 'NFPOS', ...           0
42120023                                             ['NFFRAC']           0
...                                                         ...         ...
67374258279   ['NFALG', 'NFALG', 'NFALG', 'NFALG', 'NFALG', ...           1
67384735347   ['NFGEH', 'NFVPGEH', 'NFGEH', 'NFGEH', 'NFVPGE...           1
67387668117                                  ['NFPOS', 'NFPOS']           0
67395825937   ['NFPSOVMI', 'NFPSOVMI', 'NFPSOVMI', 'NFPSOVMI...           0
67414211371                                           ['NFPOS']           0

[4435 rows x 2 columns]

In [5]:
df_lab

code_display_original,studyId_0831,CRP,Cholesterol,HbA1c,Hemoglobine,Kalium,Kreatinine,LDL Cholesterol,Natrium,Triglyceriden,eGFR (CKD-EPI),non-HDL cholesterol,HDL Cholesterol
0,7992019,1.000000,4.4,35.0,9.300000,3.900000,86.00000,1.9,143.000000,1.800000,56.000000,2.700000,1.700000
1,9812359,43.382836,4.1,36.0,9.334744,3.864681,79.70203,1.8,142.406996,1.400000,79.833819,2.900000,1.200000
2,22291801,1.000000,3.0,35.0,7.561062,3.836849,66.00000,2.1,142.000000,1.100000,88.000000,4.600000,-1.600000
3,29822615,3.000000,4.2,41.0,7.300000,4.700000,68.00000,2.0,142.000000,3.158896,74.000000,1.949091,2.250909
4,52529671,10.000000,5.2,35.0,8.700000,4.600000,174.00000,2.9,141.000000,0.800000,29.000000,3.300000,1.900000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4093,67374258279,2.979167,4.1,40.0,9.100000,4.000000,61.00000,1.9,143.000000,1.400000,85.000000,2.500000,1.600000
4094,67384735347,0.500000,6.8,38.0,9.300000,4.200000,85.00000,4.3,138.000000,1.200000,82.000000,4.800000,2.000000
4095,67387668117,75.938578,3.8,60.0,8.467428,3.939538,70.34911,1.5,138.089245,0.800000,71.529997,2.800000,1.000000
4096,67395825937,0.500000,5.6,39.0,9.400000,4.000000,66.00000,3.8,139.000000,0.800000,90.000000,4.200000,1.400000
4097,67414211371,42.000000,3.2,43.0,9.300000,4.400000,94.00000,1.6,142.000000,0.400000,60.000000,3.000000,0.200000

In [6]:
df_pat

               Age  gender
studyId_0831
7992019       78.0       1
9812359       77.0       0
22291801      59.0       1
29822615      77.0       1
42120023      62.0       1
...            ...     ...
67374258279   75.0       1
67384735347   66.0       0
67387668117   80.0       1
67395825937   71.0       0
67414211371   92.0       0

[4435 rows x 2 columns]

In [9]:
df_embeddings = df_embeddings[df_embeddings.columns[1:]].groupby('studyId_0831').mean()
df_embeddings

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,...,PC28,PC29,PC30,PC31,PC32,PC33,PC34,PC35,PC36,PC37
studyId_0831,,,,,,,,,,,,,,,,,,,,,
9812359,1.936431,1.737759,0.642923,0.353967,0.882522,0.289640,-0.518981,-0.438887,-0.216983,-0.419062,...,0.033366,0.179844,0.118571,0.056482,-0.070064,0.095458,0.054861,-0.032614,0.118550,-0.128967
22291801,3.947422,0.225223,-1.060689,-0.592915,-0.102184,0.173317,1.034117,-0.311582,0.102358,-0.113847,...,-0.023209,-0.341923,-0.357520,-0.069406,-0.056634,0.479830,-0.504835,-0.302285,0.157691,-0.367323
29822615,1.336350,-0.231479,-0.570008,-1.731272,0.335478,-0.122662,1.040301,0.316498,-0.557863,-0.560694,...,-0.328049,-0.036604,-0.015754,-0.138959,0.432715,0.178176,0.087718,-0.081861,-0.205020,0.007315
42120023,5.165613,1.143604,-1.056920,-1.837285,-2.096785,0.085966,-0.352963,1.448646,0.506342,-0.150763,...,-0.222769,0.146831,0.273729,-0.117191,-0.027510,-0.337401,0.249287,-0.045912,0.220240,0.093057
52529671,-1.810737,-2.462045,0.346055,-1.071309,0.843608,0.930051,-0.254090,-0.726229,0.498576,0.789779,...,0.279010,0.569392,-0.338695,-0.620842,0.256522,-0.278130,-0.172345,-0.346716,0.231897,0.527433
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67330610571,1.394397,-0.961820,1.069574,1.384076,-1.267348,1.706357,-0.848502,0.534462,0.062075,-0.679095,...,0.060586,-0.149536,0.754226,-0.698373,-0.246966,0.415157,0.012454,-0.492146,-0.354565,0.326544
67374258279,2.833992,1.018593,0.207366,-0.197585,-0.836917,0.424215,-0.334031,0.406223,0.298272,-0.782013,...,-0.087781,0.302531,0.348817,-0.220668,0.092497,-0.118890,0.052623,0.056421,-0.054537,-0.020910
67387668117,1.172563,1.081214,-0.271466,0.330048,0.460161,0.343571,-0.463877,-0.086343,-0.422150,-0.344843,...,0.115896,0.049533,0.015582,-0.131615,-0.038662,0.016712,0.068757,-0.034046,0.022070,-0.038226
67395825937,0.320272,1.055350,-0.132435,-0.821695,0.059982,-1.016665,0.749517,-0.334171,-0.214721,0.082267,...,0.517202,0.757330,-0.704346,0.270905,-0.569124,0.116633,0.153591,-0.311317,0.184892,0.261717
67414211371,1.551151,-0.381387,-0.317846,0.870682,0.093897,-0.632509,0.815532,-0.944024,0.090897,0.397924,...,-0.112845,0.394930,-0.150558,-0.497876,0.011677,-0.045160,-0.004058,-0.398703,0.394815,0.136261